# Prettier Configuration

# Line length
printWidth: 100

# Indentation
tabWidth: 2
useTabs: false

# Semicolons
semi: true

# Quotes
singleQuote: true

# Trailing commas
trailingComma: 'es5'

# Bracket spacing
bracketSpacing: true

# Arrow function parentheses
arrowParens: 'always'

# End of line
endOfLine: 'lf'

# JSX
jsxSingleQuote: false
jsxBracketSameLine: false

# File overrides
overrides:
  - files: '*.json'
    options:
      printWidth: 80
